name: coverity-scan
on:
  push:
    branches: [ "main" ]

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build and Submit
        run: |
          # Tải công cụ bằng mã Token của Duy
          wget https://scan.coverity.com/download/linux64 --post-data "token=${{ secrets.COVERITY_SCAN_TOKEN }}&project=${{ github.event.repository.name }}" -O coverity_tool.tgz
          mkdir coverity_tool
          tar xzf coverity_tool.tgz --strip-components=1 -C coverity_tool
          export PATH=$PWD/coverity_tool/bin:$PATH
          
          # Biên dịch Java
          chmod +x mvnw
          cov-build --dir cov-int ./mvnw clean compile
          
          # Nén và gửi bằng link chính xác từ GitHub
          tar czf myproject.tgz cov-int
          curl --form token=${{ secrets.COVERITY_SCAN_TOKEN }} \
            --form email=${{ github.actor }}@gmail.com \
            --form file=@myproject.tgz \
            --form version="v1.0" \
            "https://scan.coverity.com/builds?project=${{ github.event.repository.name }}"
